name: pytest

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '>=3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Buidl
      run: |
        echo "0.0.0-${{ github.sha }}" > version.txt
        python setup.py develop

    - name: Tests
      run: pytest
