name: pytest

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '>=3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Buidl
      run: |
        echo "0.0.0-dev" > version.txt
        python setup.py develop

#    - name: Tests
#      run: coverage run -m pytest tests

    - name: Tests
      run: |
        pytest tests --doctest-modules -v --cov-report term-missing --cov=hackernews
        pytest hackernews --pycodestyle

    - name: Coveralls
      uses: coverallsapp/github-action@v2